// In pokemon-data.ts
import { POKEMON } from "./asset_keys";

export const POKEMON_DATA = {
  // Ground Type Pokemon
  SANDSHREW: {
    PokemonId: 1,
    name: "sandshrew",
    assetKey: POKEMON.SANDSHREW,
    assetFrame: 0,
    type: "GROUND",
    baseAttack: 15,
    maxHp: 50,
    currentHp: 50,
    attackIds: [5, 7, 14, 11],
    currentLevel: 5,
    catchRate: 45,
    experience: 0,
    evolvesTo: "SANDSLASH", // Evolves at level 22
    evolutionLevel: 22,
  },
  SANDSLASH: {
    PokemonId: 25,
    name: "sandslash",
    assetKey: POKEMON.SANDSLASH,
    assetFrame: 0,
    type: "GROUND",
    baseAttack: 20,
    maxHp: 75,
    currentHp: 75,
    attackIds: [5, 7, 14, 11],
    currentLevel: 22,
    catchRate: 45,
    experience: 0,
    evolvesTo: "SANDSLASH",
    evolutionLevel: null,
  },
  
  GEODUDE: {
    PokemonId: 3,
    name: "geodude",
    assetKey: POKEMON.GEODUDE,
    assetFrame: 0,
    type: "ROCK",
    baseAttack: 16,
    maxHp: 40,
    currentHp: 40,
    attackIds: [10, 17, 5, 1],
    currentLevel: 5,
    catchRate: 40,
    experience: 0,
    evolvesTo: "GRAVELER", // Evolves at level 25
    evolutionLevel: 25,
  },
  GRAVELER: {
    PokemonId: 26,
    name: "graveler",
    assetKey: POKEMON.GRAVELER,
    assetFrame: 0,
    type: "ROCK",
    baseAttack: 22,
    maxHp: 60,
    currentHp: 60,
    attackIds: [10, 17, 5, 1],
    currentLevel: 25,
    catchRate: 40,
    experience: 0,
    evolvesTo: "GOLEM", // Evolves by trade
    evolutionLevel: null,
  },
  GOLEM: {
    PokemonId: 27,
    name: "golem",
    assetKey: POKEMON.GOLEM,
    assetFrame: 0,
    type: "ROCK",
    baseAttack: 28,
    maxHp: 80,
    currentHp: 80,
    attackIds: [10, 17, 5, 1],
    currentLevel: 30,
    catchRate: 30,
    experience: 0,
    evolvesTo: "GOLEM",
    evolutionLevel: null,
  },

  CUBONE: {
    PokemonId: 4,
    name: "cubone",
    assetKey: POKEMON.CUBONE,
    assetFrame: 0,
    type: "GROUND",
    baseAttack: 14,
    maxHp: 50,
    currentHp: 50,
    attackIds: [5, 7, 14, 3],
    currentLevel: 5,
    catchRate: 35,
    experience: 0,
    evolvesTo: "MAROWAK", // Evolves at level 28
    evolutionLevel: 28,
  },
  MAROWAK: {
    PokemonId: 28,
    name: "marowak",
    assetKey: POKEMON.MAROWAK,
    assetFrame: 0,
    type: "GROUND",
    baseAttack: 18,
    maxHp: 60,
    currentHp: 60,
    attackIds: [5, 7, 14, 3],
    currentLevel: 28,
    catchRate: 35,
    experience: 0,
    evolvesTo: "MAROWAK",
    evolutionLevel: null,
  },

  // Water Type Pokemon
  SQUIRTLE: {
    PokemonId: 6,
    name: "squirtle",
    assetKey: POKEMON.SQUIRTLE,
    assetFrame: 0,
    type: "WATER",
    baseAttack: 13,
    maxHp: 44,
    currentHp: 44,
    attackIds: [8, 15, 5, 11],
    currentLevel: 5,
    catchRate: 45,
    experience: 0,
    evolvesTo: "WARTORTLE", // Evolves at level 16
    evolutionLevel: 16,
  },
  WARTORTLE: {
    PokemonId: 29,
    name: "wartortle",
    assetKey: POKEMON.WARTORTLE,
    assetFrame: 0,
    type: "WATER",
    baseAttack: 18,
    maxHp: 59,
    currentHp: 59,
    attackIds: [8, 15, 5, 11],
    currentLevel: 16,
    catchRate: 45,
    experience: 0,
    evolvesTo: "BLASTOISE", // Evolves at level 36
    evolutionLevel: 36,
  },
  BLASTOISE: {
    PokemonId: 30,
    name: "blastoise",
    assetKey: POKEMON.BLASTOISE,
    assetFrame: 0,
    type: "WATER",
    baseAttack: 25,
    maxHp: 79,
    currentHp: 79,
    attackIds: [8, 15, 5, 11],
    currentLevel: 36,
    catchRate: 45,
    experience: 0,
    evolvesTo: "BLASTOISE",
    evolutionLevel: null,
  },

  // Fire Type Pokemon
  CHARMANDER: {
    PokemonId: 9,
    name: "charmander",
    assetKey: POKEMON.CHARMANDER,
    assetFrame: 0,
    type: "FIRE",
    baseAttack: 14,
    maxHp: 39,
    currentHp: 39,
    attackIds: [9, 16, 5, 11],
    currentLevel: 5,
    catchRate: 45,
    experience: 0,
    evolvesTo: "CHARMELEON", // Evolves at level 16
    evolutionLevel: 16,
  },
  CHARMELEON: {
    PokemonId: 31,
    name: "charmeleon",
    assetKey: POKEMON.CHARMELEON,
    assetFrame: 0,
    type: "FIRE",
    baseAttack: 18,
    maxHp: 58,
    currentHp: 58,
    attackIds: [9, 16, 5, 11],
    currentLevel: 16,
    catchRate: 45,
    experience: 0,
    evolvesTo: "CHARIZARD", // Evolves at level 36
    evolutionLevel: 36,
  },
  CHARIZARD: {
    PokemonId: 32,
    name: "charizard",
    assetKey: POKEMON.CHARIZARD,
    assetFrame: 0,
    type: "FIRE",
    baseAttack: 25,
    maxHp: 78,
    currentHp: 78,
    attackIds: [9, 16, 5, 11],
    currentLevel: 36,
    catchRate: 45,
    experience: 0,
    evolvesTo:"CHARIZARD",
    evolutionLevel: null,
  },
  BULBASAUR: {
    PokemonId: 33,
    name: "bulbasaur",
    assetKey: POKEMON.BULBASAUR,
    assetFrame: 0,
    type: "GRASS",
    baseAttack: 14,
    maxHp: 45,
    currentHp: 45,
    attackIds: [4, 12, 5, 8],
    currentLevel: 5,
    catchRate: 45,
    experience: 0,
    evolvesTo: "IVYSAUR", // Evolves at level 16
    evolutionLevel: 16,
  },
  IVYSAUR: {
    PokemonId: 34,
    name: "ivysaur",
    assetKey: POKEMON.IVYSAUR,
    assetFrame: 0,
    type: "GRASS",
    baseAttack: 18,
    maxHp: 60,
    currentHp: 60,
    attackIds: [4, 12, 5, 8],
    currentLevel: 16,
    catchRate: 45,
    experience: 0,
    evolvesTo: "VENUSAUR", // Evolves at level 32
    evolutionLevel: 32,
  },
  VENUSAUR: {
    PokemonId: 35,
    name: "venusaur",
    assetKey: POKEMON.VENUSAUR,
    assetFrame: 0,
    type: "GRASS",
    baseAttack: 25,
    maxHp: 80,
    currentHp: 80,
    attackIds: [4, 12, 5, 8],
    currentLevel: 32,
    catchRate: 45,
    experience: 0,
    evolvesTo: "VENUSAUR",
    evolutionLevel: null,
  },

  // Electric Type Pokémon
  PIKACHU: {
    PokemonId: 36,
    name: "pikachu",
    assetKey: POKEMON.PIKACHU,
    assetFrame: 0,
    type: "ELECTRIC",
    baseAttack: 15,
    maxHp: 35,
    currentHp: 35,
    attackIds: [13, 15, 5, 11],
    currentLevel: 5,
    catchRate: 190,
    experience: 0,
    evolvesTo: "RAICHU", // Evolves using Thunder Stone
    evolutionLevel: null,
  },
  RAICHU: {
    PokemonId: 37,
    name: "raichu",
    assetKey: POKEMON.RAICHU,
    assetFrame: 0,
    type: "ELECTRIC",
    baseAttack: 20,
    maxHp: 60,
    currentHp: 60,
    attackIds: [13, 15, 5, 11],
    currentLevel: 16,
    catchRate: 75,
    experience: 0,
    evolvesTo: "RAICHU",
    evolutionLevel: null,
  },

  ELECTRIKE: {
    PokemonId: 38,
    name: "electrike",
    assetKey: POKEMON.ELECTRIKE,
    assetFrame: 0,
    type: "ELECTRIC",
    baseAttack: 17,
    maxHp: 40,
    currentHp: 40,
    attackIds: [13, 15, 5, 11],
    currentLevel: 5,
    catchRate: 45,
    experience: 0,
    evolvesTo: "MANECTRIC", // Evolves at level 26
    evolutionLevel: 26,
  },
  MANECTRIC: {
    PokemonId: 39,
    name: "manectric",
    assetKey: POKEMON.MANECTRIC,
    assetFrame: 0,
    type: "ELECTRIC",
    baseAttack: 25,
    maxHp: 70,
    currentHp: 70,
    attackIds: [13, 15, 5, 11],
    currentLevel: 26,
    catchRate: 45,
    experience: 0,
    evolvesTo:"MANECTRIC",
    evolutionLevel: null,
  },

  // Normal Type Pokémon
  MEOWTH: {
    PokemonId: 40,
    name: "meowth",
    assetKey: POKEMON.MEOWTH,
    assetFrame: 0,
    type: "NORMAL",
    baseAttack: 12,
    maxHp: 40,
    currentHp: 40,
    attackIds: [1, 3, 5, 8],
    currentLevel: 5,
    catchRate: 255,
    experience: 0,
    evolvesTo: "PERSIAN", // Evolves at level 28
    evolutionLevel: 28,
  },
  PERSIAN: {
    PokemonId: 41,
    name: "persian",
    assetKey: POKEMON.PERSIAN,
    assetFrame: 0,
    type: "NORMAL",
    baseAttack: 20,
    maxHp: 65,
    currentHp: 65,
    attackIds: [1, 3, 5, 8],
    currentLevel: 28,
    catchRate: 90,
    experience: 0,
    evolvesTo: "PERSIAN",
    evolutionLevel: null,
  },

  // Flying Type Pokémon
  PIDGEY: {
    PokemonId: 42,
    name: "pidgey",
    assetKey: POKEMON.PIDGEY,
    assetFrame: 0,
    type: "FLYING",
    baseAttack: 12,
    maxHp: 40,
    currentHp: 40,
    attackIds: [2, 6, 5, 9],
    currentLevel: 5,
    catchRate: 255,
    experience: 0,
    evolvesTo: "PIDGEOTTO", // Evolves at level 18
    evolutionLevel: 18,
  },
  PIDGEOTTO: {
    PokemonId: 43,
    name: "pidgeotto",
    assetKey: POKEMON.PIDGEOTTO,
    assetFrame: 0,
    type: "FLYING",
    baseAttack: 20,
    maxHp: 63,
    currentHp: 63,
    attackIds: [2, 6, 5, 9],
    currentLevel: 18,
    catchRate: 120,
    experience: 0,
    evolvesTo: "PIDGEOT", // Evolves at level 36
    evolutionLevel: 36,
  },
  PIDGEOT: {
    PokemonId: 44,
    name: "pidgeot",
    assetKey: POKEMON.PIDGEOT,
    assetFrame: 0,
    type: "FLYING",
    baseAttack: 25,
    maxHp: 83,
    currentHp: 83,
    attackIds: [2, 6, 5, 9],
    currentLevel: 36,
    catchRate: 45,
    experience: 0,
    evolvesTo:"PIDGEOT",
    evolutionLevel: null,
  },

  // Fire Type Pokémon
  VULPIX: {
    PokemonId: 45,
    name: "vulpix",
    assetKey: POKEMON.VULPIX,
    assetFrame: 0,
    type: "FIRE",
    baseAttack: 15,
    maxHp: 38,
    currentHp: 38,
    attackIds: [9, 16, 5, 10],
    currentLevel: 5,
    catchRate: 190,
    experience: 0,
    evolvesTo: "NINETALES", // Evolves using Fire Stone
    evolutionLevel: null,
  },
  NINETALES: {
    PokemonId: 46,
    name: "ninetales",
    assetKey: POKEMON.NINETALES,
    assetFrame: 0,
    type: "FIRE",
    baseAttack: 24,
    maxHp: 73,
    currentHp: 73,
    attackIds: [9, 16, 5, 10],
    currentLevel: 16,
    catchRate: 75,
    experience: 0,
    evolvesTo: "NINETALES",
    evolutionLevel: null,
  },
};

  // Add similar structure for other Pokémon…
